question_data = [
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "History",
            "question": "The United States Department of Homeland Security was formed in response to the September 11th attacks.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "History",
            "question": "In World War II, Hawker Typhoons served in the Pacific theater.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "History",
            "question": "Abraham Lincoln was the first U.S. President to be born outside the borders of the thirteen original states. ",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "History",
            "question": "If you grab the bladed end of a longsword in a specific way, you will not cut yourself.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "History",
            "question": "The United States of America declared their independence from the British Empire on July 4th, 1776.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "History",
            "question": "United States President Ronald Reagan was the first president to appoint a woman to the Supreme Court. ",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "History",
            "question": "In 1967, a magazine published a story about extracting hallucinogenic chemicals from bananas to raise moral questions about banning drugs.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "History",
            "question": "The Hundred Years&#039; War was fought for more than a hundred years.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "History",
            "question": "Sir Issac Newton served as a Member of Parliament, but the only recorded time he spoke was to complain about a draft in the chambers.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "History",
            "question": "Oxford University is older than the Aztec Empire. ",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
    ]